object Versions {
    const val espresso = "3.5.1"
    const val junit = "4.13.2"
    const val junitExt = "1.1.5"
    const val testCore = "1.2.0-alpha05"
    const val constraintLayout = "2.1.4"
    const val design = "1.8.0"
    const val coreKtx = "1.8.0"
    const val supportLibrary = "1.5.0"
    const val gradleAndroidPlugin = "7.0.4"
    const val kotlin = "1.6.10"
    const val timber = "5.0.1"
    const val navigationComponent = "2.5.2"
    const val hilt = "2.42"
    const val safeArgsPlugin = "2.4.1"
    const val adapterDelegate = "4.3.0"
    const val gson = "2.8.8"
}